### PR TITLE
skip distributions with missing metadata

### PR DESCRIPTION
**Pull request by tlambert03**
fixes plugin discovery if a user has a distribution with missing metadata

https://github.com/napari/napari/pull/1357#issuecomment-692280799

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM!

This looks good, but I wonder if this whole thing should be in a try/ catch sort of call in case other packages could do weird things. Thoughts?

I was trying to figure out which package was causing the problem for me, but I couldn't, printing `dist.metadata` gave loads of text, was hard to tell what was going on. Any ideas?

**Comment by tlambert03** [comment]
Without knowing what those other things might be, I'm a bit hesitant to put in a general `except Exception` just yet... This was just a proper bug, since `dist.metadata.get("name")` _can_ be none.  I should have checked for it. 

for your package, try running:
```
for d in importlib_metadata.distributions():
    if not d.metadata.get("name"):
        print(d.files)
```

maybe the files will reveal something?

**Comment by sofroniewn** [comment]
> I'm a bit hesitant to put in a general except Exception just yet... 

That's fine, something we can look into in future too

> maybe the files will reveal something?

I just get `None`!

**Comment by tlambert03** [comment]
oh, actually use `d._path` instead of `d.files`

**Comment by sofroniewn** [comment]
Culprit is  `/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/pandas-1.0.1.dist-info`!

**Comment by sofroniewn** [comment]
Which is funny as pip freeze says `pandas==1.0.3` ...

**Comment by tlambert03** [comment]
yeah, strange... must be a botched uninstall?

**Comment by sofroniewn** [comment]
> yeah, strange... must be a botched uninstall?

Yup, deleting it manually fixes issue even without this PR, but this was still good to fix. Thanks, and thanks for the help identifying the bad package!!

**Pull request merged**
