### PR TITLE
Warn when plugin module had no hooks

### PR DESCRIPTION
**Pull request by tlambert03**
This emits a warning when a plugin module is registered that provides no hooks.  @jni, this would have helped us both realize the issue as you would have at least seen a warning in your logs (or, if you had internal warnings set to errors with `-W error`, it would have replaced the error message with:

```
E           UserWarning: Module 'affinder' from plugin 'affinder' has no hooks! Consider disabling or uninstalling this plugin. If you are a developer, please check your entry point module.
```

### CODE REVIEW

**Comment by jni** [comment]
@tlambert03 I don't know what this message would have helped me as my original impression was that npe/npe2 would recursively check submodules... So there needs to be some clue that you mean "affinder *and only affinder*".

**Comment by tlambert03** [comment]
We can modify the message, I tried to indicate that by using the word     "Module" in "Module 'affinder' from plugin 'affinder'"

Suggestions on how to change that?

**Comment by tlambert03** [comment]
Ohhh, sorry, you thought it would recurse I see... 

Well, yeah, no 😂.  I could say at the end here "this doesn't recursively import all of your sub modules"?

**Comment by tlambert03** [comment]
> Suggestions on how to change that?

@jni, I'd personally really like to have this warning in there.  It's a simple check: "let me know when I've pointed to a module that has no hooks".  please see my comment above that I tried to indicate that by using the word "Module" in "Module 'affinder' from plugin 'affinder'".  If you don't have a better suggestion can approve please?

**Comment by tlambert03** [comment]
@jni, will give this a few more days then merging

**Pull request merged**
