### PR TITLE
migrate pypi related code from napari core

### LINKED ISSUE #13: migrate pypi code from napari core repo to plugin engine
To facilitate the upcoming alpha cohort of plugin development, I am looking into building some basic functions and infrastructure for plugin devs to quickly check the validity of their on-going dev work. I am thinking we should move the checks from the main repo (https://github.com/napari/napari/blob/master/napari/plugins/pypi.py )to the plugin engine to aggregate the checks to one place, the end goal is to provide developers access to a command-line or pytest module that they can use to test their setup in the same way as plugin engine does, without importing the napari core. thoughts?

### PR DESCRIPTION
**Pull request by ziyangczi**
migrate pypi related code to plugin engine to allow access from plugin dependencies without importing napari

closes #13

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM! But maybe @tlambert03 can comment before merge. I think (see https://github.com/napari/napari-plugin-engine/issues/13#issuecomment-768678050) that once the next version of the npe is released we'd drop this code from napari and just depend on it from here, right?

**Comment by tlambert03** [comment]
I'm a touch apprehensive about just copy-pasting this from napari and opening up as a public API.  This was pretty much _only_ ever used by me in the `qt_plugin_dialog` in napari and not conceived thinking about public usage.  The tests are rather minimal, and the API is a bit haphazard.  As I said before, I'm not totally opposed to it, but I'm not super excited about the two-package problem here either (so would probably be inclined to not delete the code from napari anytime soon).

Just curious, how/where do we imagine people using this?

**Comment by ziyangczi** [comment]
> I'm a touch apprehensive about just copy-pasting this from napari and opening up as a public API. This was pretty much _only_ ever used by me in the `qt_plugin_dialog` in napari and not conceived thinking about public usage. The tests are rather minimal, and the API is a bit haphazard. As I said before, I'm not totally opposed to it, but I'm not super excited about the two-package problem here either (so would probably be inclined to not delete the code from napari anytime soon).
> 
> Just curious, how/where do we imagine people using this?

we will allow people to run these checks in their CI/CD after the deployment step to check it is discoverable by napari, and I do have another upcoming story to make this more bullet proof, with the hope that we can remove the original code eventually from napari

**Comment by tlambert03** [comment]
k

**Review by tlambert03 — APPROVED** [review]

**Comment by ziyangczi** [comment]
may I trouble someone with write access to merge this one for me? :)

**Pull request merged**
